# ------------------------------------------------Environment Settings------------------------------------------------#
gpu_id: "7,4,5,6"

# -------------------------------------------------Retrieval Settings------------------------------------------------#
# If set the name, the model path will be find in global paths
retrieval_method: "/share/project/models/e5-base-v2"  # name or path of the retrieval model.
index_path: "/share/project/weiyifan/AutoTIR/retrieval_data/retrieval-index/data00/jiajie_jin/flashrag_indexes/wiki_dpr_100w/e5_flat_inner.index" # path to the indexed file
faiss_gpu: True # whether use gpu to hold index
corpus_path: "/share/project/weiyifan/AutoTIR/retrieval_data/retrieval-corpus/wiki18_100w.jsonl"  # path to corpus in '.jsonl' format that store the documents